To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News


Unsloth's [Docker image](https://hub.docker.com/r/unsloth/unsloth) is here! Start training with no setup & environment issues. [Read our Guide](https://docs.unsloth.ai/new/how-to-train-llms-with-unsloth-and-docker).

[gpt-oss RL](https://docs.unsloth.ai/new/gpt-oss-reinforcement-learning) is now supported with the fastest inference & lowest VRAM. Try our [new notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/gpt-oss-(20B)-GRPO.ipynb) which creates kernels!

Introducing [Vision](https://docs.unsloth.ai/new/vision-reinforcement-learning-vlm-rl) and [Standby](https://docs.unsloth.ai/basics/memory-efficient-rl) for RL! Train Qwen, Gemma etc. VLMs with GSPO - even faster with less VRAM.

Unsloth now supports Text-to-Speech (TTS) models. Read our [guide here](https://docs.unsloth.ai/basics/text-to-speech-tts-fine-tuning).

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation

In [ ]:
%%capture
import os, re
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    # Do this only in Colab notebooks! Otherwise use pip install unsloth
    import torch; v = re.match(r"[0-9\.]{3,}", str(torch.__version__)).group(0)
    xformers = "xformers==" + ("0.0.32.post2" if v == "2.8.0" else "0.0.29.post3")
    !pip install --no-deps bitsandbytes accelerate {xformers} peft trl triton cut_cross_entropy unsloth_zoo
    !pip install sentencepiece protobuf "datasets>=3.4.1,<4.0.0" "huggingface_hub>=0.34.0" hf_transfer
    !pip install --no-deps unsloth
!pip install transformers==4.55.4
!pip install --no-deps trl==0.22.2

### Unsloth

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 8146 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 15 trillion tokens model 2x faster!
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # We also uploaded 4bit for 405b!
    "unsloth/Mistral-Nemo-Base-2407-bnb-4bit", # New Mistral 12b 2x faster!
    "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit",
    "unsloth/mistral-7b-v0.3-bnb-4bit",        # Mistral v3 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: Could not import trl.trainer.alignprop_trainer: Failed to import trl.trainer.alignprop_trainer because of the following error (look up to see its traceback):
Failed to import trl.models.modeling_sd_base because of the following error (look up to see its traceback):
Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
JITCallable._set_src() takes 1 positional argument but 2 were given
Unsloth: Could not import trl.trainer.ddpo_trainer: Failed to import trl.trainer.ddpo_trainer because of the following error (look up to see its traceback):
Failed to import trl.models.modeling_sd_base because of the following error (look up to see its traceback):
Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
JITCallable._set_src() takes 1 positional argument but 2 were given
==((====))==  Unsloth 2025.12.9: Fast Llama patching. Transformers: 4.55.4.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.318 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/5.96G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/235 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/459 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2025.12.9 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the Alpaca dataset from [yahma](https://huggingface.co/datasets/yahma/alpaca-cleaned), which is a filtered version of 52K of the original [Alpaca dataset](https://crfm.stanford.edu/2023/03/13/alpaca.html). You can replace this code section with your own data prep.

**[NOTE]** To train only on completions (ignoring the user's input) read TRL's docs [here](https://huggingface.co/docs/trl/sft_trainer#train-on-completions-only).

**[NOTE]** Remember to add the **EOS_TOKEN** to the tokenized output!! Otherwise you'll get infinite generations!

If you want to use the `llama-3` template for ShareGPT datasets, try our conversational [notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Alpaca.ipynb)

For text completions like novel writing, try this [notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Mistral_(7B)-Text_Completion.ipynb).

In [ ]:
#abrir ventana para cargar dataset
from google.colab import files
uploaded = files.upload()

Saving legal_dataset_final_tacusi_con.json to legal_dataset_final_tacusi_con.json

In [ ]:
#cargar dataset
import json

with open("legal_dataset_final_tacusi_con.json", "r", encoding="utf-8-sig") as f:
    data = json.load(f)

print(f"Se cargaron {len(data)} ejemplos.")
#Función para dividir textos largos en fragmentos tokenizados compatibles con el modelo
def split_long_texts(dataset, tokenizer, max_tokens):
    new_dataset = []
    for sample in dataset:
        tokens = tokenizer.encode(sample["text"])#Esto convierte el texto completo en una lista de tokens (números que representan palabras, subpalabras o caracteres).
        for i in range(0, len(tokens), max_tokens):
            chunk_tokens = tokens[i:i+max_tokens]#Un fragmento de tokens del texto original. Es una lista de números,
            chunk_text = tokenizer.decode(chunk_tokens)#El texto en lenguaje natural que corresponde a esos tokens
            new_dataset.append({"text": chunk_text})
    return new_dataset

Se cargaron 201 ejemplos.

In [ ]:
alpaca_prompt = """Redacta un informe legal siguiendo estrictamente la estructura:

I. ANTECEDENTES:
II. BASE LEGAL:
III. ANÁLISIS:
IV. CONCLUSIÓN:
V. RECOMENDACIONES:

Asegúrate de *no terminar el texto sin incluir todas las secciones*.
Finaliza siempre con RECOMENDACIONES.

### Instruction:
{}

### Input:
{}

### Output:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input, output in zip(instructions, inputs, outputs):
        # Must add EOS_TOKEN, otherwise your generation will go on forever!
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }

#importar dataset
from datasets import Dataset
from datasets import load_dataset
dataset = Dataset.from_list(data)
dataset = dataset.map(formatting_prompts_func, batched = True,)

Map:   0%|          | 0/201 [00:00<?, ? examples/s]

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support TRL's `DPOTrainer`!

In [ ]:
from trl import SFTConfig, SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 40,
        learning_rate = 2e-4,
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/201 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

In [ ]:
# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

GPU = NVIDIA A100-SXM4-80GB. Max memory = 79.318 GB.
7.135 GB of memory reserved.

In [ ]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 201 | Num Epochs = 2 | Total steps = 40
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040 of 8,072,204,288 (0.52% trained)

In [ ]:
# alpaca_prompt = Copied from above
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
inputs = tokenizer(
[
    alpaca_prompt.format(
        "Aprobacion de plan de gobierno digital", # instruction
        "INFORME N°094-2025-UEI/OPP/MPC-BPR \nA        : Lic. Edder Joshimar Warthon Gamarra \nJefe de la Oficina de Planificación y Presupuesto \nDE      : Brady Palma Rodríguez \nEncargado de la Unidad de Estadística e Informática \nASUNTO : Solicitud de informe legal para aprobación del Plan de Gobierno Digital \nREFERENCIA : Plan de Gobierno Digital – Municipalidad Provincial de Calca, versión \npreliminar 2025 \nFECHA : Calca, 02 de agosto del 2025 \nMe dirijo a usted para saludarlo cordialmente y, a la vez, informar que la Unidad de \nEstadística e Informática ha culminado la elaboración del documento preliminar del Plan \nde Gobierno Digital de la Municipalidad Provincial de Calca, correspondiente al \nperiodo 2025–2027, en el marco del cumplimiento de la Política Nacional de \nTransformación Digital y las disposiciones emitidas por la Secretaría de Gobierno y \nTransformación Digital de la PCM. \nANTECEDENTES \nLa implementación del Plan de Gobierno Digital es una acción estratégica que responde a \nlos lineamientos establecidos por el Decreto Supremo N.º 029-2021-PCM y la Ley N.º \n1412, Ley de Gobierno Digital. \nEn este sentido, se ha trabajado un documento técnico que contiene los objetivos, líneas \nde acción, metas, responsables y cronograma de actividades, que busca fortalecer el \necosistema digital institucional, garantizar la interoperabilidad, impulsar la identidad y \nservicios digitales, y promover la seguridad digital. \nCabe señalar que la aprobación del presente plan requiere contar previamente con el \ninforme legal correspondiente, el cual determine la viabilidad normativa y sujeción a las \ndisposiciones vigentes. \nANÁLISIS \nLa emisión del informe legal permitirá sustentar formal y legalmente la aprobación del \nPlan de Gobierno Digital, a fin de remitirlo posteriormente al Pleno del Concejo Municipal, \ny así cumplir con su implementación de acuerdo con la normativa nacional. \nEste procedimiento es imprescindible para garantizar la legalidad de las acciones \ninstitucionales en el marco del proceso de transformación digital en la Municipalidad \nProvincial de Calca. \nCONCLUSIÓN \nPor lo expuesto, se solicita de manera formal la emisión del informe legal \ncorrespondiente, a fin de continuar con el procedimiento de aprobación del Plan de \nGobierno Digital de la Municipalidad Provincial de Calca. \nSin otro particular, quedo atento a cualquier consulta o documentación adicional que se \nrequiera para el trámite correspondiente. \nAtentamente", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 2000, use_cache = True)
tokenizer.batch_decode(outputs)

['<|begin_of_text|>Redacta un informe legal siguiendo estrictamente la estructura:\n\nI. ANTECEDENTES:\nII. BASE LEGAL:\nIII. ANÁLISIS:\nIV. CONCLUSIÓN:\nV. RECOMENDACIONES:\n\nAsegúrate de *no terminar el texto sin incluir todas las secciones*.\nFinaliza siempre con RECOMENDACIONES.\n\n### Instruction:\nAprobacion de plan de gobierno digital\n\n### Input:\nINFORME N°094-2025-UEI/OPP/MPC-BPR \nA        : Lic. Edder Joshimar Warthon Gamarra \nJefe de la Oficina de Planificación y Presupuesto \nDE      : Brady Palma Rodríguez \nEncargado de la Unidad de Estadística e Informática \nASUNTO : Solicitud de informe legal para aprobación del Plan de Gobierno Digital \nREFERENCIA : Plan de Gobierno Digital – Municipalidad Provincial de Calca, versión \npreliminar 2025 \nFECHA : Calca, 02 de agosto del 2025 \nMe dirijo a usted para saludarlo cordialmente y, a la vez, informar que la Unidad de \nEstadística e Informática ha culminado la elaboración del documento preliminar del Plan \nde Gobierno Digital de la Municipalidad Provincial de Calca, correspondiente al \nperiodo 2025–2027, en el marco del cumplimiento de la Política Nacional de \nTransformación Digital y las disposiciones emitidas por la Secretaría de Gobierno y \nTransformación Digital de la PCM. \nANTECEDENTES \nLa implementación del Plan de Gobierno Digital es una acción estratégica que responde a \nlos lineamientos establecidos por el Decreto Supremo N.º 029-2021-PCM y la Ley N.º \n1412, Ley de Gobierno Digital. \nEn este sentido, se ha trabajado un documento técnico que contiene los objetivos, líneas \nde acción, metas, responsables y cronograma de actividades, que busca fortalecer el \necosistema digital institucional, garantizar la interoperabilidad, impulsar la identidad y \nservicios digitales, y promover la seguridad digital. \nCabe señalar que la aprobación del presente plan requiere contar previamente con el \ninforme legal correspondiente, el cual determine la viabilidad normativa y sujeción a las \ndisposiciones vigentes. \nANÁLISIS \nLa emisión del informe legal permitirá sustentar formal y legalmente la aprobación del \nPlan de Gobierno Digital, a fin de remitirlo posteriormente al Pleno del Concejo Municipal, \ny así cumplir con su implementación de acuerdo con la normativa nacional. \nEste procedimiento es imprescindible para garantizar la legalidad de las acciones \ninstitucionales en el marco del proceso de transformación digital en la Municipalidad \nProvincial de Calca. \nCONCLUSIÓN \nPor lo expuesto, se solicita de manera formal la emisión del informe legal \ncorrespondiente, a fin de continuar con el procedimiento de aprobación del Plan de \nGobierno Digital de la Municipalidad Provincial de Calca. \nSin otro particular, quedo atento a cualquier consulta o documentación adicional que se \nrequiera para el trámite correspondiente. \nAtentamente\n\n### Output:\nediante el presente me dirijo a Ud. en atención al Proveído dispuesto por su Despacho así como del Informe remitido por el Jefe de la Oficina de Planificación y Presupuesto, Abog. Edder Joshimar Warthon Gamarra, por el cual se solicita pronunciamiento legal respecto a la APROBACION DEL PLAN DE GOBIERNO DIGITAL DE LA MUNICIPALIDAD PROVINCIAL DE CALCA, lo que se emite según los siguientes fundamentos que se expone.\nI. ANTECEDENTES:\n1.1. - Mediante Proveído de Gerencia Municipal N° 1193-2025-MPC-GM de fecha 02 de agosto del 2025, se solicita pronunciamiento legal respecto a la APROBACION DEL PLAN DE GOBIERNO DIGITAL DE LA MUNICIPALIDAD PROVINCIAL DE CALCA, elevado por el Jefe de la Oficina de Planificación y Presupuesto, Abog. Edder Joshimar Warthon Gamarra.\nII. BASE LEGAL:\n• Constitución Política del Perú\n• Ley N° 27972, Ley Orgánica de Municipalidades\n• Ley N° 27444, Ley del Procedimiento Administrativo General\n• Decreto Supremo N° 029-2021-PCM, que aprueba la Política Nacional de Transformación Digital.\n• Ley N° 1412, Ley de Gobierno Digital.\nIII. ANÁLISIS:\n3.1. - Que, conforme a las facultades otorgadas a las Municipalidades en el artículo 194° de la Constitución Política del Perú, modificada por la Ley de Reforma Constitucional N° 28607, en Concordancia con lo establecido en el Artículo II del Título Preliminar de la Ley Orgánica de Municipalidades N° 27972, establece que los Gobiernos Locales gozan de Autonomía política, económica y administrativa en los asuntos de su competencia, radicando esta autonomía en la facultad de ejercer actos de gobierno administrativo y de administración, con sujeción al ordenamiento jurídico.\n3.2. - Que, estando a lo establecido en el Artículo IV. Principios del procedimiento administrativo que preceptúa al Principio de legalidad: Las autoridades administrativas deben actuar con respeto a la Constitución, la ley y al derecho, dentro de las facultades que le estén atribuidas y de acuerdo con los fines para los que les fueron conferidas.\n3.3. - Que, el Artículo VIII del Título Preliminar de la Ley Orgánica de Municipalidades, establece que: “Los gobiernos locales están sujetos a las leyes y disposiciones que, de manera general y de conformidad con la Constitución Política del Perú, regulan las actividades y funcionamiento del Sector Público, así como las normas técnicas referidas a los servicios y bienes públicos, y a los sistemas administrativos del Estado que por su naturaleza son de observancia y cumplimiento obligatorio”;\n3.4. - Que, de conformidad con el Decreto Legislativo N° 1440, que crea el Sistema Nacional de Gobierno Digital, en adelante el SGD, en su Artículo 4° numeral 4.1 establece que los Gobiernos Regionales y Locales, en el marco de la Política Nacional de Gobierno Digital, deben desarrollar las siguientes funciones: 4.1.1. Funciones específicas de los Gobiernos Regionales: a) Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. b) Promover el desarrollo de la identidad digital regional, en coordinación con el Ente rector. c) Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. d) Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. e) Administrar los servicios digitales regionales, de conformidad con lo establecido en el Reglamento. f) Administrar los servicios digitales de gobierno local, de conformidad con lo establecido en el Reglamento. 4.1.2. Funciones específicas de los Gobiernos Locales: a) Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. b) Promover el desarrollo de la identidad digital local, en coordinación con el Ente rector. c) Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. d) Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. e) Administrar los servicios digitales locales, de conformidad con lo establecido en el Reglamento. Que, el Decreto Legislativo N° 1440, en su Artículo 5°, establece que los gobiernos regionales y locales, en el marco de la Política Nacional de Gobierno Digital, deben desarrollar las siguientes funciones: 5.1. Funciones específicas de los gobiernos regionales: 5.1.1. Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. 5.1.2. Promover el desarrollo de la identidad digital regional, en coordinación con el Ente rector. 5.1.3. Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. 5.1.4. Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. 5.1.5. Administrar los servicios digitales regionales, de conformidad con lo establecido en el Reglamento. 5.1.6. Administrar los servicios digitales de gobierno local, de conformidad con lo establecido en el Reglamento. 5.2. Funciones específicas de los gobiernos locales: 5.2.1. Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. 5.2.2. Promover el desarrollo de la identidad digital local, en coordinación con el Ente rector. 5.2.3. Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. 5.2.4. Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. 5.2.5. Administrar los servicios digitales locales, de conformidad con lo establecido en el Reglamento. Que, mediante Decreto Supremo N° 029-2021-PCM se aprueba la Política Nacional de Transformación Digital, el cual en su Artículo 6° establece que los gobiernos regionales y locales, en el marco de la Política Nacional de Transformación Digital, deben desarrollar las siguientes funciones: 6.1. Funciones específicas de los gobiernos regionales: 6.1.1. Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. 6.1.2. Promover el desarrollo de la identidad digital regional, en coordinación con el Ente rector. 6.1.3. Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. 6.1.4. Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. 6.1.5. Administrar los servicios digitales regionales, de conformidad con lo establecido en el Reglamento. 6.1.6. Administrar los servicios digitales de gobierno local, de conformidad con lo establecido en el Reglamento. 6.2. Funciones específicas de los gobiernos locales: 6.2.1. Promover el desarrollo de las capacidades digitales de su jurisdicción, en coordinación con el Ente rector. 6.2.2. Promover el desarrollo de la identidad digital local, en coordinación con el Ente rector. 6.2.3. Implementar el uso de los servicios digitales nacionales, de conformidad con lo establecido en el Reglamento. 6.2.4. Promover la interoperabilidad de sus sistemas digitales con los del nivel nacional y local, de conformidad con lo establecido en el Reglamento. 6.2.5. Administrar los servicios digit']

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
# Guardar el modelo y el tokenizer en carpeta local
output_dir = "/content/drive/MyDrive/informes_legales_ai2/modelo_finetuned"

trainer.save_model(output_dir)        # Guarda pesos, config y tokenizer
tokenizer.save_pretrained(output_dir) # Guarda el tokenizer

('/content/drive/MyDrive/informes_legales_ai2/modelo_finetuned/tokenizer_config.json',
 '/content/drive/MyDrive/informes_legales_ai2/modelo_finetuned/special_tokens_map.json',
 '/content/drive/MyDrive/informes_legales_ai2/modelo_finetuned/tokenizer.json')

In [ ]:
from unsloth import FastLanguageModel

# Cargar tu modelo entrenado
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = output_dir,
    max_seq_length = 8192,
    dtype = None,
    load_in_4bit = True,
)

# Exportar fusionado (ya con LoRA aplicado al modelo base)
merged_dir = "/content/drive/MyDrive/informes_legales_ai2/modelo_fusionado"
model.save_pretrained(merged_dir)
tokenizer.save_pretrained(merged_dir)

print("✅ Modelo fusionado guardado en:", merged_dir)

==((====))==  Unsloth 2025.12.9: Fast Llama patching. Transformers: 4.55.4.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.318 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
✅ Modelo fusionado guardado en: /content/drive/MyDrive/informes_legales_ai2/modelo_fusionado

In [ ]:
from unsloth import FastLanguageModel

# === Ruta donde está tu modelo entrenado con LoRA ===
output_dir = "/content/drive/MyDrive/informes_legales_ai2/modelo_finetuned"

# === Ruta donde guardarás el modelo ya fusionado (LoRA + base) ===
merged_dir = "/content/drive/MyDrive/informes_legales_ai2/modelo_fusionado"

# === Cargar el modelo entrenado (ya tiene LoRA aplicado) ===
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=output_dir,
    max_seq_length=8192,
    dtype=None,             # deja que autodetecte (float16, bfloat16, etc.)
    load_in_4bit=True       # o False si usaste full precision
)

# === GUARDAR MODELO FUSIONADO ===
model.save_pretrained(merged_dir)
tokenizer.save_pretrained(merged_dir)

print("✅ Modelo fusionado guardado correctamente en:", merged_dir)

==((====))==  Unsloth 2025.12.9: Fast Llama patching. Transformers: 4.55.4.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.318 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
✅ Modelo fusionado guardado correctamente en: /content/drive/MyDrive/informes_legales_ai2/modelo_fusionado

In [ ]:
import gradio as gr
from unsloth import FastLanguageModel
import torch

# ==========================
# 1. Cargar modelo finetune
# ==========================
model_path = "/content/drive/MyDrive/informes_legales_ai2/modelo_fusionado"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_path,
    max_seq_length = 8192,
    dtype = None,
    load_in_4bit = True,
)

FastLanguageModel.for_inference(model)  # modo inferencia

# ==========================
# 2. Función de inferencia
# ==========================
def generar_informe(texto_usuario):
    instruction = """Redacta un informe legal siguiendo estrictamente la estructura:

I. ANTECEDENTES:
II. BASE LEGAL:
III. ANÁLISIS:
IV. CONCLUSIÓN:
V. RECOMENDACIONES:

Asegúrate de *terminar el texto con toda estructura*.
Finaliza siempre con RECOMENDACIONES
"""

    prompt = f"""
### Instruction:
{instruction}

### Input:
{texto_usuario}

### Output:
"""

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")
    output = model.generate(
        **inputs,
        max_new_tokens=2200,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.2
    )
    decoded = tokenizer.decode(output[0], skip_special_tokens=True)

    # Extraer solo el texto generado
    return decoded.split("### Output:")[-1].strip()

# ==========================
# 3. Interfaz Gradio con Blocks
# ==========================
with gr.Blocks(title="Generador de Informes Legales") as demo:
    gr.Markdown("## 🏛️ Generador de Informes Legales\nModelo finetuneado en informes de la Municipalidad de Calca")

    with gr.Row():
        entrada = gr.Textbox(lines=12, label="Ingrese los datos del Informe Legal", interactive=True)
        boton = gr.Button("Generar Informe")

    salida = gr.Textbox(lines=60, label="Informe Legal Generado", visible=False)
    boton_nuevo = gr.Button("🔁 Generar otro informe", visible=False)

    def ejecutar(texto):
        informe = generar_informe(texto)
        return gr.update(visible=False), gr.update(value=informe, visible=True), gr.update(visible=True)

    def reiniciar():
        return gr.update(value="", visible=True), gr.update(visible=False), gr.update(visible=False)

    boton.click(fn=ejecutar, inputs=entrada, outputs=[entrada, salida, boton_nuevo])
    boton_nuevo.click(fn=reiniciar, outputs=[entrada, salida, boton_nuevo])

demo.launch(share=True)

==((====))==  Unsloth 2025.12.9: Fast Llama patching. Transformers: 4.55.4.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.318 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://0db8aba19f54189119.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
#RADIO 2
import gradio as gr
from unsloth import FastLanguageModel
import torch

# ==========================
# 1. Cargar modelo finetune
# ==========================
model_path = "/content/drive/MyDrive/informes_legales_ai2/modelo_fusionado"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_path,
    max_seq_length = 8192,
    dtype = None,
    load_in_4bit = True,
)

# ==========================
# 2. Función de inferencia
# ==========================
def generar_informe(texto_usuario):
    instruction = """ Usa únicamente la información contenida en el documento siguiente. No uses ni recuerdes datos de entrenamientos anteriores ni
    información externa. Si la información no está en el documento, responde: "No hay información suficiente en el documento para responder".
    siguiendo estrictamente la estructura:

I. ANTECEDENTES:
II. BASE LEGAL:
III. ANÁLISIS:
IV. CONCLUSIÓN:
V. RECOMENDACIONES:

Asegúrate de *terminar el texto con toda estructura*.
Finaliza siempre con RECOMENDACIONES
"""

    prompt = f"""
### Instruction:
{instruction}

### Input:
{texto_usuario}

### Output:
"""

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")
    output = model.generate(
        **inputs,
        max_new_tokens=2200,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.2
    )
    decoded = tokenizer.decode(output[0], skip_special_tokens=True)

    # Extraer solo el texto generado
    return decoded.split("### Output:")[-1].strip()

# ==========================
# 3. Interfaz Gradio con Blocks
# ==========================
with gr.Blocks(title="Generador de Informes Legales") as demo:
    gr.Markdown("## 🏛️ Generador de Informes Legales\nModelo finetuneado en informes de la Municipalidad de Calca")

    with gr.Row():
        entrada = gr.Textbox(lines=12, label="Ingrese los datos del Informe Legal", interactive=True)
        boton = gr.Button("Generar Informe")

    salida = gr.Textbox(lines=60, label="Informe Legal Generado", visible=False)
    boton_nuevo = gr.Button("🔁 Generar otro informe", visible=False)

    def ejecutar(texto):
        informe = generar_informe(texto)
        return gr.update(visible=False), gr.update(value=informe, visible=True), gr.update(visible=True)

    def reiniciar():
        return gr.update(value="", visible=True), gr.update(visible=False), gr.update(visible=False)

    boton.click(fn=ejecutar, inputs=entrada, outputs=[entrada, salida, boton_nuevo])
    boton_nuevo.click(fn=reiniciar, outputs=[entrada, salida, boton_nuevo])

demo.launch(share=True)

In [ ]:
#RADIO 3
import gradio as gr
from unsloth import FastLanguageModel
import torch

# ==========================
# 1. Cargar modelo finetune
# ==========================
model_path = "/content/drive/MyDrive/informes_legales_ai2/modelo_fusionado"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_path,
    max_seq_length = 8192,
    dtype = None,
    load_in_4bit = True,
)

FastLanguageModel.for_inference(model)  # modo inferencia

# ==========================
# 2. Definir secciones del informe
# ==========================
SECCIONES = [
    "I. ANTECEDENTES:",
    "II. BASE LEGAL:",
    "III. ANÁLISIS:",
    "IV. CONCLUSIÓN:",
    "V. RECOMENDACIONES:"
]

def generar_seccion(texto_usuario, seccion, informe_parcial):
    instruction = f"""Redacta exclusivamente la sección "{seccion}" de un informe legal.

- No repitas información ya generada en secciones anteriores.
- No incluyas encabezados o textos de otras secciones.
- Mantén la sección clara y completa, específica para el caso.
- Usa solo la información relevante del texto de entrada.

Informe parcial ya generado:
{informe_parcial}
"""

    prompt = f"""
### Instruction:
{instruction}

### Input:
{texto_usuario}

### Output:
"""

    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")
    output = model.generate(
        **inputs,
        max_new_tokens=600,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.2,
        do_sample=True,
        eos_token_id=tokenizer.eos_token_id
    )
    decoded = tokenizer.decode(output[0], skip_special_tokens=True)
    resultado = decoded.split("### Output:")[-1].strip()

    if seccion not in resultado:
        resultado = f"{seccion}\n{resultado}"

    return resultado

def generar_informe_seccional(texto_usuario):
    informe_completo = ""
    for seccion in SECCIONES:
        texto_seccion = generar_seccion(texto_usuario, seccion, informe_completo)
        informe_completo += texto_seccion + "\n\n"

    return informe_completo.strip()
# ==========================
# 5. Interfaz Gradio con Blocks
# ==========================
with gr.Blocks(title="Generador de Informes Legales") as demo:
    gr.Markdown("## 🏛️ Generador de Informes Legales\nModelo finetuneado en informes de la Municipalidad de Calca")

    with gr.Row():
        entrada = gr.Textbox(lines=12, label="Ingrese los datos del Informe Legal", interactive=True)
        boton = gr.Button("Generar Informe")

    salida = gr.Textbox(lines=60, label="Informe Legal Generado", visible=False)
    boton_nuevo = gr.Button("🔁 Generar otro informe", visible=False)

    def ejecutar(texto):
        informe = generar_informe_seccional(texto)
        return gr.update(visible=False), gr.update(value=informe, visible=True), gr.update(visible=True)

    def reiniciar():
        return gr.update(value="", visible=True), gr.update(visible=False), gr.update(visible=False)

    boton.click(fn=ejecutar, inputs=entrada, outputs=[entrada, salida, boton_nuevo])
    boton_nuevo.click(fn=reiniciar, outputs=[entrada, salida, boton_nuevo])

demo.launch(share=True)

In [ ]:
# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

In [ ]:
# alpaca_prompt = Copied from above
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
inputs = tokenizer(
[
    alpaca_prompt.format(
        "Continue the fibonnaci sequence.", # instruction
        "1, 1, 2, 3, 5, 8", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
model.save_pretrained("lora_model")  # Local saving
tokenizer.save_pretrained("lora_model")
# model.push_to_hub("your_name/lora_model", token = "...") # Online saving
# tokenizer.push_to_hub("your_name/lora_model", token = "...") # Online saving

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

In [ ]:
if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model) # Enable native 2x faster inference

# alpaca_prompt = You MUST copy from above!

inputs = tokenizer(
[
    alpaca_prompt.format(
        "What is a famous tall tower in Paris?", # instruction
        "", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

You can also use Hugging Face's `AutoModelForPeftCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
if False:
    # I highly do NOT suggest - use Unsloth if possible
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
        "lora_model", # YOUR MODEL YOU USED FOR TRAINING
        load_in_4bit = load_in_4bit,
    )
    tokenizer = AutoTokenizer.from_pretrained("lora_model")

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_16bit", token = "")

# Merge to 4bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_4bit", token = "")

# Just LoRA adapters
if False:
    model.save_pretrained("model")
    tokenizer.save_pretrained("model")
if False:
    model.push_to_hub("hf/model", token = "")
    tokenizer.push_to_hub("hf/model", token = "")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [Wiki page](https://github.com/unslothai/unsloth/wiki#gguf-quantization-options)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("hf/model", tokenizer, token = "")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "f16", token = "")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q4_k_m", token = "")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "hf/model", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "",
    )

Now, use the `model-unsloth.gguf` file or `model-unsloth-Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>